### ISSUE TITLE
SVI with numpyro - question

### ISSUE THREAD

**Issue by soldierofhell** [thomaspinder/GPJax#35]
Hi @thomaspinder,
I'm a little bit confused about inference with numpyro that is presented in https://github.com/thomaspinder/GPJax/blob/master/docs/nbs/numpyro_interface.ipynb .
After optimization in numpyro we obtain final_parameters, that's clear. But then we're using standard functions with those final_parameters, but everything else (posterior, training_ds) is left like in "exact" inference. 
```
meanf = gpx.mean(posterior, learned_params, training_ds)
varf = gpx.variance(posterior, learned_params, training_ds)


mu = meanf(xtest).squeeze()
cov = varf(xtest).squeeze()
```

My question is basicly: do we use the approximate SVI distribution here? My goal is to speed up inference, in particular to not use training_ds.
Also one additional question: can I use
```
gpjax.save(posterior, 'test')
```
to save SVI model?

Regards,

**Comment by jejjohnson** [comment]
Hi,

So in this specific example it actually uses the exact marginal likelihood estimation (MLL) (a mistype on my part because it is not approximate). You can see that the guide is empty which means that numpyro SVI optimizes the parameters as per MLL. The other demo (using the `AutoDelta` guide) would give you the same parameters because it is a MAP estimation but the learned parameters names would be the same. MLL and MAP only find the kernel parameters and observation noise in the likelihood. So to answer your question: we are are using these learned parameters found from the **exact inference** method which was **trained** via the numpyro SVI. 

Regarding speeding up inference: by **inference** do you mean for finding the hyper-parameters given the data or do you mean doing **predictions**? I'm assuming you mean for the predictions (but correct me if I'm wrong!). In that case, the `training_ds` is needed to calculate the intermediate matrices needed for the GP predictive mean and variance functions. For example calculating the weights and such so you need to have the original training data to do so ([details here](https://github.com/thomaspinder/GPJax/blob/master/gpjax/predict.py#L14)).  The numpyro svi object doesn't return these natively so we must calculate them ourselves. **Note**: numpyro does have some other nuggets where we can use the guide to obtain all of these intermediate matrices (e.g. [example](http://num.pyro.ai/en/stable/tutorials/bayesian_regression.html?highlight=predictive#Posterior-Predictive-Distribution)).

Regarding Saving: So I wasn't aware of that functionality in GPJax. At least not within the latest version so @thomaspinder will have to comment on that. In the meantime, a nice thing about saving/loading is that it works just like standard python so you can use pickle (or joblib) and save all of the components. So for example you could save the `posterior, learned_params, training_ds` together in a pickle file for later. And then for predictions, you can just use the `gpx.mean, gpx.variane` again. Unfortunately you cannot save the `mean, variance` functions themselves because there are context variables within that function which don't play well with pickle.


I hope that answers your question. Let me know if it does not.

**Comment by soldierofhell** [comment]
Thank you @jejjohnson for detailed answer. I guess I have to get acquainted with theory details. Basically I'd like to speed predictions (of course finding hyper-parameters too), actually do something similar to https://docs.gpytorch.ai/en/stable/examples/04_Variational_and_Approximate_GPs/SVGP_Regression_CUDA.html#Making-Predictions, but in JAX. I suspect I'm missing what they call **Variational strategy**
> This tells us how to transform a distribution q(u) over the inducing point values to a distribution q(f) over the latent function values for some input x.

As for the saving I've double checked this and it seems like it disappeared after refactoring of the code, it was introduced by PR https://github.com/thomaspinder/GPJax/pull/15

Regards,

**Comment by thomaspinder** [comment]
Hi @soldierofhell, I think your describing the variational free energy model from Titsias 2009. We are currently looking to support this (see #31), however, it is currently incomplete due to a few missing terms in the ELBO. 

Regarding the saving functionality, this was from a previous iteration of GPJax which used ObJax as a dependency. We have since dropped this dependency and moved to a "pure Jax" implementation. I agree with @jejjohnson that pickling the objects makes most sense, though I'd be happy to re-introduce an interface for saving/loading models again if it's something you'd find useful.

**Comment by mkolodziejczyk-piap** [comment]
Thanks @thomaspinder, I will get familiar with this PR. In the meantime I'm investigating HMC example that @jejjohnson suggested and it looks promising.

Regards,
