### ISSUE TITLE
Working with Optax

### ISSUE THREAD

**Issue by pharringtonp19** [thomaspinder/GPJax#37]
Seems like a really nice library! 

Is it possible to work with optimizers defined via optax rather than from jax.eperimental?

**Comment by jejjohnson** [comment]
Hey!

So everything should work with `optax`. In fact, it's probably recommended that you use `optax` because it removes a lot of the boilerplate code. 

---
**Demo PseudoCode**

In principle, you shouldn't have to change much. In the [regression example](https://gpjax.readthedocs.io/en/latest/nbs/regression.html), you would first change where you define the optimizer. There are minimal changes here. Then you also have to change the training loop as well. Again, not many changes are needed.

**Jax**

```python
opt_init, opt_update, get_params = optimizers.adam(step_size=0.01)
opt_state = opt_init(params)

def step(iteration, opt_state):
    params = get_params(opt_state)
    loss_val, grads = jax.value_and_grad(mll)(params, training)
    opt_state = opt_update(iteration, grads, opt_state)
    return opt_state, loss_val
```

**Optax**

```python
optimizer = optax.adam(0.01)
opt_state = optimizer.init(params)

def step(opt_state):
    loss_val, grads = jax.value_and_grad(mll)(params, training)
    updates, opt_state = optimizer.update(grads, opt_state)  # transform & update stats.
    params = optax.apply_updates(params, updates)  # update the parameters.
    return opt_state, loss_val
```

This is pseudocode but I believe the above should work. Let me know if it doesn't!
